services:

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    volumes:
      - vmdata:/victoria-metrics-data
    command:
      - "-storageDataPath=/victoria-metrics-data"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.145.0
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317" # grpc
      - "4318:4318" # http
    depends_on:
      - victoria-metrics

  flask-app:
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - otel-collector

volumes:
  vmdata:
